### ISSUE TITLE
Missing event/function description

### ISSUE THREAD

**Issue by daniel-schel** [research-virtualfortknox/node-red-contrib-msb#4]
A missing input for the description of an event or function.

**To Reproduce**
1. Add a msb object
1. Go to properties of msb object
2. Click on events or functions
3. Add new event or function
4. There are only entries for name and data format of the event, not for the description

**Expected behavior**
Besides the input for name and data format of the event, there should also be an input for a description.

**Screenshots**
![image](https://user-images.githubusercontent.com/41727382/90759593-eb82f000-e2e0-11ea-8c09-49ecda429074.png)
![image](https://user-images.githubusercontent.com/41727382/90759602-f178d100-e2e0-11ea-8b73-083a739a24a7.png)

**Environment:**
 - node-red-contrib-msb version v1.0.0

**Comment by ipamaas** [comment]
Solved in current release 1.0.1
